---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    default_schema: tm
    hbm2ddl:
        schema_filter_provider: cn.edu.bnuz.bell.orm.BellSchemaFilterProvider

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver
    dialect: cn.edu.bnuz.bell.orm.PostgreSQL95Dialect
    configClass: cn.edu.bnuz.bell.orm.BellHibernateMappingContextConfiguration

environments:
    development:
        dataSource:
            dbCreate: validate
            logSql: true
    test:
        dataSource:
            dbCreate: update
    production:
        dataSource:
            dbCreate: update
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
---
grails:
    profile: web
    codegen:
        defaultPackage: cn.edu.bnuz.bell
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

security:
    oauth2:
        client:
            accessTokenUri: http://localhost/uaa/oauth/token
            userAuthorizationUri: http://localhost/uaa/oauth/authorize
            clientId: acme
            clientSecret: acmesecret
            scope: openid
        resource:
            userInfoUri: http://localhost/uaa/user

zuul:
    routes:
        api:
            path: /api/**
            url: http://localhost:9000/api

server:
    session:
        timeout: 1200

logging:
    level:
#        org.springframework.security: DEBUG

bell:
    orm:
        ignored:
            schemas:
                - 'ea'
            viewPrefix: 'dv_'
    student:
        picturePath: 'D:\bell\bell-tm-pictures'
---
spring.cloud.netflix.metrics.enabled: false